spring.application.name: msPrincingService

springdoc.show-actuator: true

management.endpoints.web.exposure.include: '*'
management:
  endpoint.health:
    show-details: always
    probes:
      enabled: true